<# 
================================================================================
 Anavem.com - PowerShell Script
================================================================================
 Script Name : Anavem-SystemInventory.ps1
 Description : Collects Windows hardware and OS inventory and writes to TXT file
 Author      : Anavem.com
 Version     : 1.1.1
 Website     : https://www.anavem.com

 Use Case    :
 - System inventory
 - IT support diagnostics
 - Asset documentation
 - Intune / RMM reporting

 Run as Admin: No
================================================================================
#>

# Ensure output directory exists
$OutputDir = "C:\Scripts"
if (-not (Test-Path $OutputDir)) {
    New-Item -Path $OutputDir -ItemType Directory -Force | Out-Null
}

# File name with timestamp
$Timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
$OutputFile = "$OutputDir\Anavem-SystemInventory_$Timestamp.txt"

# Collect system information
$cs   = Get-CimInstance Win32_ComputerSystem
$os   = Get-CimInstance Win32_OperatingSystem
$cpu  = Get-CimInstance Win32_Processor | Select-Object -First 1
$bios = Get-CimInstance Win32_BIOS

# Build output
$Inventory = @"
Anavem.com : Windows System Inventory
Script   : Anavem-SystemInventory.ps1
Version  : 1.1.0
Generated: $(Get-Date)
------------------------------------------------------------

Computer Name : $env:COMPUTERNAME
Manufacturer  : $($cs.Manufacturer)
Model         : $($cs.Model)

Operating System : $($os.Caption)
OS Version       : $($os.Version)
OS Build         : $($os.BuildNumber)

BIOS Version : $($bios.SMBIOSBIOSVersion)
Serial No.   : $($bios.SerialNumber)

CPU  : $($cpu.Name)
RAM  : $([math]::Round($cs.TotalPhysicalMemory / 1GB, 2)) GB

Uptime : $((Get-Date) - $os.LastBootUpTime)

------------------------------------------------------------
Generated by Anavem.com
"@

# Write to file
$Inventory | Out-File -FilePath $OutputFile -Encoding UTF8

# Optional console confirmation (safe if run manually)
Write-Host "Inventory saved to $OutputFile"
